module.exports = function (finyear,curryear) {

    console.log("finyear"+finyear+"--"+curryear);

    this.master = { Address: "address",
                    City: "city",
                    Company: "company",
                    CompanySettings: "companysettings",
                    UserCompany: "user_company",
                    Country: "country",
                    Currency: "currency",
                    Customer: "customer",
                    Measurement: "measurement",
                    LedgerGroup: "ledgergroup",
                    Ledger_Services: "ledger_services",
                    Mapping: "mapping",
                    MappingSchemes: "mappingschemes",
                    Product: "product",
                    ProductCategory: "productcategory",
                    ProductDocs: "productdocs",
                    State: "state",
                    Supplier: "supplier",
                    TaxAgency: "taxagency",
                    TaxCodes: "taxcodes",
                    TDSRates: "tdsrates",
                    Users: "users",
                    Modules: "module",
                    Permission: "permission",
                    Entity: "entity",
                    UserRoles: "user_roles",
                    UserRolePermission: "user_role_permission",
                    UserMap: "user_map",
                    Roles: "roles",
                    RolesPermission: "roles_permission",
                    Plans: "plans",
                    AddOns: "add_ons",
                    PlanAddOns: "plan_add_ons",
                    Orders: "orders",
                    Subscription: "user_subscription",
                    SubscriptionAddOns: "subscription_add_ons",
                    SubscriptionLicenses: "subscription_licenses",
                    LicenseAddOns: "license_add_ons",
                    Import: "import"};

    let data='';
    if(finyear!=curryear){
        data = {Acct_LedgerTxn: finyear+"_acct_ledgertxn",
                Acct_PaymentDetails: finyear+"_acct_paymentdetails",
                Acct_Tdstxn: finyear+"_acct_tdstxn",
                Acct_TransactionParticulars: finyear+"_acct_transactionparticulars",
                Acct_Transactions: finyear+"_acct_transactions",
                Inv_LedgerTxn: finyear+"_inv_ledgertxn",
                Inv_AttributeType: finyear+"_inv_attributetype",
                Inv_AttributeValue: finyear+"_inv_attributevalue",
                Inv_Brand: finyear+"_inv_brand",
                Inv_DeliveryNote: finyear+"_inv_deliverynote",
                Inv_ProductLot: finyear+"_inv_productlot",
                Inv_Region: finyear+"_inv_region",
                Inv_RequisitionRequest: finyear+"_inv_requisitionrequest",
                Inv_RequisitionRequestItems: finyear+"_inv_requisitionrequestitems",
                Inv_Stock: finyear+"_inv_stock",
                Inv_StockLocation: finyear+"_inv_stocklocation",
                Inv_StockTrack: finyear+"_inv_stocktrack",
                Inv_Zone: finyear+"_inv_zone",
                Ledger: finyear+"_ledger",
                LedgerHistory: finyear+"_ledgerhistory",
                PaymentReceipt: finyear+"_paymentreceipt",
                PurchaseInvoice: finyear+"_purchaseinvoice",
                PurchaseInvoiceItems: finyear+"_purchaseinvoiceitems",
                PurchaseInvoiceTaxes: finyear+"_purchaseinvoicetaxes",
                PurchaseOrder: finyear+"_purchaseorder",
                PurchaseOrderItems: finyear+"_purchaseorderitems",
                PurchaseOrderTaxes: finyear+"_purchaseordertaxes",
                SaleInvoice: finyear+"_saleinvoice",
                SaleInvoiceItems: finyear+"_saleinvoiceitems",
                SaleInvoiceTaxes: finyear+"_saleinvoicetaxes",
                Journal: finyear+"_journal",
                JournalTaxes: finyear+"_journaltaxes"};

    }else{
        data= {Acct_LedgerTxn: "acct_ledgertxn",
                Acct_PaymentDetails: "acct_paymentdetails",
                Acct_Tdstxn: "acct_tdstxn",
                Acct_TransactionParticulars: "acct_transactionparticulars",
                Acct_Transactions: "acct_transactions",
                Address: "address",
                City: "city",
                Company: "company",
                CompanySettings: "companysettings",
                UserCompany: "user_company",
                Country: "country",
                Currency: "currency",
                Customer: "customer",
                Measurement: "measurement",
                Inv_LedgerTxn: "inv_ledgertxn",
                Inv_AttributeType: "inv_attributetype",
                Inv_AttributeValue: "inv_attributevalue",
                Inv_Brand: "inv_brand",
                Inv_DeliveryNote: "inv_deliverynote",
                Inv_ProductLot: "inv_productlot",
                Inv_Region: "inv_region",
                Inv_RequisitionRequest: "inv_requisitionrequest",
                Inv_RequisitionRequestItems: "inv_requisitionrequestitems",
                Inv_Stock: "inv_stock",
                Inv_StockLocation: "inv_stocklocation",
                Inv_StockTrack: "inv_stocktrack",
                Inv_Zone: "inv_zone",
                Ledger: "ledger",
                LedgerGroup: "ledgergroup",
                LedgerHistory: "ledgerhistory",
                Ledger_Services: "ledger_services",
                Mapping: "mapping",
                MappingSchemes: "mappingschemes",
                PaymentReceipt: "paymentreceipt",
                Product: "product",
                ProductCategory: "productcategory",
                ProductDocs: "productdocs",
                PurchaseInvoice: "purchaseinvoice",
                PurchaseInvoiceItems: "purchaseinvoiceitems",
                PurchaseInvoiceTaxes: "purchaseinvoicetaxes",
                PurchaseOrder: "purchaseorder",
                PurchaseOrderItems: "purchaseorderitems",
                PurchaseOrderTaxes: "purchaseordertaxes",
                SaleInvoice: "saleinvoice",
                SaleInvoiceItems: "saleinvoiceitems",
                SaleInvoiceTaxes: "saleinvoicetaxes",
                Journal: "journal",
                JournalTaxes: "journaltaxes",
                State: "state",
                Supplier: "supplier",
                TaxAgency: "taxagency",
                TaxCodes: "taxcodes",
                TDSRates: "tdsrates",
                Users: "users",
                Modules: "module",
                Permission: "permission",
                Entity: "entity",
                UserRoles: "user_roles",
                UserRolePermission: "user_role_permission",
                UserMap: "user_map",
                Roles: "roles",
                RolesPermission: "roles_permission",
                Plans: "plans",
                AddOns: "add_ons",
                PlanAddOns: "plan_add_ons",
                Orders: "orders",
                Subscription: "user_subscription",
                SubscriptionAddOns: "subscription_add_ons",
                SubscriptionLicenses: "subscription_licenses",
                LicenseAddOns: "license_add_ons",
                Import: "import"};
    }
    
    this.txn=data;
    this.tbls = function () {
        if(finyear!=curryear){
            return { ...this.master, ...this.txn };
        }else{
            return {...this.txn};  
        }
    }
}

